import { readFileSync } from "node:fs";

const files = [
  "public/index.html",
  "public/app.js",
  "public/admin.html",
  "public/admin.js",
  "public/simulator.html",
  "public/simulator.css",
  "public/simulator.js",
  "api/support-ticket.js",
  "api/support-simulator.js",
  "api/admin-config.js",
  "api/support-config.js",
  "api/jira.js",
  "api/slack-list-schema.js",
  "api/account-settings.js",
  "api/auth.js",
  "api/livechat-webhook.js",
  "lib/account-store.js",
  "lib/ai-provider.js",
  "lib/attachment-policy.js",
  "lib/case-action-executor.js",
  "lib/case-action-context.js",
  "lib/case-action-store.js",
  "lib/case-bridge-tools.js",
  "lib/case-draft.js",
  "lib/case-decision-engine.js",
  "lib/case-investigation-trace.js",
  "lib/case-knowledge.js",
  "lib/case-operation-contracts.js",
  "lib/ai-training.js",
  "lib/case-orchestrator.js",
  "lib/case-read-tools.js",
  "lib/case-response-policy.js",
  "lib/case-verified-actions.js",
  "lib/case-store.js",
  "lib/case-workflows.js",
  "lib/livechat-case-parser.js",
  "lib/safe-template-replies.js",
  "lib/remote-config.js",
  "lib/jira.js",
  "lib/slack.js",
  "lib/http.js",
  "lib/integration-policy.js",
  "lib/atena-connector-scheduler.js",
  "lib/kyc-bridge-store.js",
  "lib/kyc-connector-scheduler.js",
  "lib/kyc-extraction.js",
  "lib/kyc-review-store.js",
  "lib/livechat-webhook-security.js",
  "lib/login-rate-limit.js",
  "lib/simulator-policy.js",
  "lib/support-simulator.js",
  "lib/audit.js",
  "scripts/deploy-with-env.mjs",
  "scripts/build-manual-knowledge.py",
  "scripts/start-livechat-connectors.mjs",
  "scripts/sync-openai-knowledge.mjs",
  "scripts/extract-support10-response-candidates.mjs",
  "scripts/curate-support10-response-candidates.mjs",
  "scripts/integrate-approved-support10-templates.mjs",
  "scripts/mine-livechat-conversation-flows.mjs",
  "scripts/test-ai-provider.mjs",
  "scripts/test-admin-account-provisioning.mjs",
  "scripts/test-atena-connector-scheduler.mjs",
  "scripts/test-bob-request-contract.mjs",
  "scripts/test-api-route-consolidation.mjs",
  "scripts/test-support10-template-integration.mjs",
  "scripts/test-auto-safe-templates.mjs",
  "scripts/test-case-orchestrator.mjs",
  "scripts/test-case-action-executor.mjs",
  "scripts/test-supervised-case-flow.mjs",
  "scripts/test-case-action-provider-verification.mjs",
  "scripts/test-case-action-store.mjs",
  "scripts/test-case-bridge-tools.mjs",
  "scripts/test-case-draft.mjs",
  "scripts/test-case-investigation-trace.mjs",
  "scripts/test-case-knowledge.mjs",
  "scripts/test-case-operation-contracts.mjs",
  "scripts/test-case-read-tools.mjs",
  "scripts/test-real-conversation-regression.mjs",
  "scripts/test-case-response-policy.mjs",
  "scripts/test-case-verified-actions.mjs",
  "scripts/test-integration-policy.mjs",
  "scripts/test-jira-account-settings.mjs",
  "scripts/test-kyc-connector-scheduler.mjs",
  "scripts/test-kyc-extraction.mjs",
  "scripts/test-kyc-review-store.mjs",
  "scripts/test-livechat-attachments.mjs",
  "scripts/test-livechat-webhook-limits.mjs",
  "scripts/test-livechat-webhook-security.mjs",
  "scripts/test-simulator-policy.mjs",
  "scripts/test-slack-list-7-only.mjs",
  "scripts/test-support-simulator-boundary.mjs",
  "scripts/test-support-simulator.mjs",
  "scripts/test-widget-access.mjs",
  "scripts/test-all.mjs",
  "docs/agent-operations-program.md",
  "docs/atena-kyc-orchestrator-evidence.md",
  "docs/bob-livechat-connector.md",
  "docs/kyc-livechat-connector-stable.md",
  "docs/case-orchestrator.md",
  "docs/livechat-console-checklist.md",
  "docs/plan-soporte-livechat-app.md",
  "docs/betxico-soporte-knowledge.md",
  "docs/betxico_base_conocimiento_operativa_v1.md",
  "docs/betxico_intents_dataset_v1.json",
  "docs/support-remote-config.example.json",
  "knowledge/betxico-support-manual.v1.json"
];

for (const file of files) {
  readFileSync(new URL(`../${file}`, import.meta.url), "utf8");
}

JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
JSON.parse(readFileSync(new URL("../vercel.json", import.meta.url), "utf8"));
JSON.parse(readFileSync(new URL("../docs/support-remote-config.example.json", import.meta.url), "utf8"));
JSON.parse(readFileSync(new URL("../docs/betxico_intents_dataset_v1.json", import.meta.url), "utf8"));
JSON.parse(readFileSync(new URL("../docs/betxico_fallback_templates_v1.json", import.meta.url), "utf8"));
JSON.parse(readFileSync(new URL("../knowledge/betxico-support-manual.v1.json", import.meta.url), "utf8"));
if (readFileSync(new URL("../tmp/livechat-response-mining/plantillas_aprobadas_soporte10_v1.json", import.meta.url), "utf8")) {
  JSON.parse(readFileSync(new URL("../tmp/livechat-response-mining/plantillas_aprobadas_soporte10_v1.json", import.meta.url), "utf8"));
}

console.log("Scaffold de soporte valido.");
